### ISSUE TITLE
Fewer OA policy reminder emails sent than anticipated

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#1014]
This week's batch of OA policy reminder emails was much smaller than anticipated. 

- It appears that 43 users received reminders today. 
- The email cap is set at 200 (I updated it from 100 to 200 on October 22). 
- The overarching organization, "The Pennsylvania State University" contains 1197 people "users needing OA email." That's as of October 28, and technically some of those people could have become eligible for an email since the emails went out. However, there were 1241 people needing an email as of October 22, so I would be surprised if all those folks disappeared from the list and a new group of almost the same size came back. 
 
I suspect there's a bug preventing emails from sending.

**Comment by anaelizabethenriquez** [comment]
Still not sure what's going on here, but 200 people received reminder emails today, as planned.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Sorry, I wanted to look into this sooner.  Looks like there were some network issues during that time.  The emails started to go out and then stopped with this error: `Net::ReadTimeout · Net::ReadTimeout with #<TCPSocket:(closed)>`.

For those with bugsnag access: https://app.bugsnag.com/penn-state/researcher-metadata/errors/66f0d9d93e88313d208646c1?filters[error.status]=open&filters[event.since]=30d&event_id=671efe5701099b6912060000

This wasn't rescued and logged in our `EmailErrors` (https://metadata.libraries.psu.edu/admin/email_error), though.  I can add a ticket to address that issue, but this issue can be closed.

**Comment by anaelizabethenriquez** [comment]
Sounds good; thanks!

**Comment by anaelizabethenriquez** [comment]
I don't want to reopen this, but I do want to note that there was some kind of error with the emails sent on November 25, likely same as above, and only 25 emails went out.

**Comment by ajkiessl** [comment]
Yeah, looks like the same problem: Net::ReadTimeout with #<TCPSocket:(closed)> https://app.bugsnag.com/penn-state/researcher-metadata/errors/66f0d9d93e88313d208646c1?filters[error.status]=open&filters[event.since]=30d .  #1018 should help manage this, but I'm wondering if Sunday night is not a good time to send out emails.  Maybe network issues are common Sunday nights for some reason?  This time was shifted a bit when we changed our infrastructure.  We originally wanted the emails to go out Monday morning.  I added a comment in #1018 about this.
