### ISSUE TITLE
Add check for API in Nagios

### ISSUE THREAD

**Issue by njnash** [psu-libraries/researcher-metadata#45]
We have fairly thorough Nagios monitoring for the production site infrastructure, but in terms of verifying functionality of the application, all that we really have is a basic check to see that the home page loads correctly. We should add a check that verifies that the API documentation is working and that the API itself is working.

Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-14

**Comment by ajkiessl** [comment]
@off2seethewizard Here is the link to the documentation: https://metadata.libraries.psu.edu/api_docs .  We'll probably want to check that we get a 200 response from this.

We can try hitting the organization endpoint since it will be quick to test the actual API: https://metadata.libraries.psu.edu/v1/organizations

**Comment by off2seethewizard** [comment]
these checks have been added to nagios.  going to close this out
