### ISSUE TITLE
Where to view logic for duplicate grouping and auto-merging

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#523]
As we are prepare for the third of four sprints, I'd like to take another look at the logic for grouping duplicates as well as the logic on the two auto-merging procedures, to see if there are other improvements we should aim for before we wrap up this development round. (We have a lot of new duplicate groups because of the improvements to the AI importer, and non-merged and/or non-grouped duplicates can lead to other issues down the line, such as double ScholarSphere deposits.)

@ajkiessl can you point me to somewhere I could look at that logic? (Would the code be readable to me?)

**Comment by ajkiessl** [comment]
The code may be difficult to interpret in some places and less so in other places.  

This is the core of the logic that assigns duplicates:
https://github.com/psu-libraries/researcher-metadata/blob/main/app/models/duplicate_publication_group.rb#L20-L35
It basically takes a publication and does some querying of the database to find fuzzy matches based on the combined title and subtitle.  It then checks that the matched publications have the same published year.  If the publication in question is not an AI import, the search also checks that the dois match (or are blank).

This is the core of the logic to merge publications that have a single AI publication and a single Pure publication.  The code here may be easier to read:
https://github.com/psu-libraries/researcher-metadata/blob/main/app/models/duplicate_publication_group.rb#L73-L94

The logic for matching and merging based on doi is more complicated and more difficult to articulate.  This is the code to do the matching: https://github.com/psu-libraries/researcher-metadata/blob/main/app/models/publication_match_on_doi_policy.rb
This is the code to do the merging: https://github.com/psu-libraries/researcher-metadata/blob/main/app/models/publication_merge_on_doi_policy.rb
There is also this logic to merge contributors when doi merging: https://github.com/psu-libraries/researcher-metadata/blob/main/app/models/contributor_name_merge_policy.rb
This was the ticket where we sussed most of this out: https://github.com/psu-libraries/researcher-metadata/issues/374. It explains some of what's going on.

To complicate all of this a little bit more, we have merge policies for some of the associated data to publications:
-Authorships: https://github.com/psu-libraries/researcher-metadata/blob/main/app/models/authorship_merge_policy.rb
-Open Access Locations: https://github.com/psu-libraries/researcher-metadata/blob/main/app/models/open_access_location_merge_policy.rb

**Comment by ajkiessl** [comment]
Linking to tests as well since they articulate most of the logic in human readable language.  They also give examples which may be helpful.  Some of the code I linked to below I've highlighted in yellow to identify what is important.  Some I have not since the whole file is important:

Assigning duplicates: https://github.com/psu-libraries/researcher-metadata/blob/main/spec/component/models/duplicate_publication_group_spec.rb#L23-L370 .  This may be a little confusing since there is a lot there.  The 'finds similar publications and groups them' chunk of code tells us which publications defined above were marked as duplicates.

Matching based on doi: https://github.com/psu-libraries/researcher-metadata/blob/main/spec/component/models/publication_match_on_doi_policy_spec.rb
Merging based on doi: https://github.com/psu-libraries/researcher-metadata/blob/main/spec/component/models/publication_merge_on_doi_policy_spec.rb
Merging contributors (done when dois match and are merged): https://github.com/psu-libraries/researcher-metadata/blob/main/spec/component/models/contributor_name_merge_policy_spec.rb

Authorship merging logic: https://github.com/psu-libraries/researcher-metadata/blob/main/spec/unit/models/authorship_merge_policy_spec.rb
Open access location merging logic: https://github.com/psu-libraries/researcher-metadata/blob/main/spec/component/models/open_access_location_merge_policy_spec.rb

In all the above code, anywhere you see 'describe', 'context', or 'it'  followed by some human readable text, that text will tell you what the logic is.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Here are some rough thoughts I have here. Sharing them in case you get a chance to read before we meet.

General question: Currently the process errs in the direction of not grouping/not merging. There are significant downsides to this, especially the large backlog of items to merge. What would be the downsides to erring in the other direction?

### Duplicate grouping: Date of publication
Rather than requiring same publication year, change to +/-2 — so 2020 would match 2018, 2019, 2020, 2021, 2022
Less aggressive change would be to move to +/-1 — maybe check each one to see how much of a difference it makes

Change would be needed in grouping logic, AI-Pure automerger (maybe?)
No change needed in DOI auto merger, which ignores date of publication

How much would this help? Of 56,512 pubs since January 2019, 5490 have exactly the same title as another publication from that time period, but 3100 of the 5490 (57%) are not in a duplicate group. (This would likely help even more, since we’re not requiring exact matches on titles. This was just the easiest for me to check. Note that I didn’t really check pub date nearness in this estimate.)


### Duplicate grouping: Same DOI
Could we add logic to group items as duplicates if they have the same DOI? The trouble with doing this is that the DOI automerger relies on the duplicate grouping on order to check that the titles are similar. So if we add this and also make the changes I’m suggesting below on the DOI auto merge, we’d basically be auto merging based on DOI alone, which we don’t want. 

As things are now, we’re missing a lot of duplicate grouping because of this. From 2019-01-01 to 2022-09-06, there are 56,512 pubs. 38,593 have DOIs present. 4,193 (7.4% of total) have same DOI value as another pub from that date range. 2,628 of those (63%) are not in a duplicate group.

### AI-Pure automerger
Am I understanding correctly that this only merges if the duplicate group contains exactly one item from AI and one from Pure? (Or does it just do one at a time and loop, the way the DOI automerger does?) Is that to make it easier to figure out which fields to keep, or to avoid contributors issues? Or maybe this is about preventing merge on common titles (e.g., Introduction). It’s fairly common to have two or more AI imports for a publication due to multiple authors entering it, so it would be nice to be able to auto-merge those with the Pure import.

Does this process require any fields to match exactly, or is being in the duplicate group sufficient? If it doesn’t, I’m concerned it’s currently overbroad.

What is stopping group 71509 from automerging under this process? Does the presence of AI imports on the pub that has a Pure import prevent this merge? 

Given how few existing duplicate groups have a DOI for more than one pub, I think focusing on this automerger would help the most with existing duplicates.


### DOI automerger (PublicationMatchOnDoiPolicy)
General note: I’m suggesting we get rid of a lot of requirements here. Could we also take some of the stricter logic here, tighten it up more, and use it to merge publications that don’t share a DOI, perhaps in the AI-Pure automerger?

Titles — Recommend to ignore. Since this process only runs on duplicate groups, we know that the combined title and subtitle match reasonably well. We’re also requiring an exact DOI match. I think we could eliminate any further title matching requirement. I see a lot of typos in titles coming from AI, and occasional ones from Pure — mostly things like a missing “the,” etc.

Journal — Recommend to ignore.
	⁃	Alex accounted for ampersands in the last development round.
	⁃	Typos are an issue.
	⁃	Abbreviations are an issue (e.g., “Astrophysical Journal” is the same as “ApJ”).
	⁃	Journals with subtitles are an issue, e.g., “Alzheimer's & dementia : the journal of the Alzheimer's Association” is the journal for one duplicate and “Alzheimer’s and dementia” is the journal for another in the same group.

Volume, Issue, Edition, Pages — Recommend to ignore. There is some weird stuff in these fields. We may need to update merging rules.

Publication type — Since AI and Pure use totally different vocabularies here, I’d like to write up a list of things that can count as matches. I think this could be handled as a separate issue from the rest. I will need lists of the two platforms’ contribution types in order to do this. 

How much would changes to the DOI automerger help?
If my OpenRefine work is correct, at least 1129 duplicate groups contain at least two publications with the same DOI. This is a fairly small percentage of the groups. Only 858 additional duplicate groups have more than one DOI present. (9158 groups contain at most one DOI.)

**Comment by ajkiessl** [comment]
@anaelizabethenriquez To answer the general question above, the biggest downside of erring on the side of merging would be if we get too loose and end up with a very large amount of false positives.  This could put us in a difficult spot where we'll need to identify what imports from what system need to be separated.  I think it would probably be pretty difficult to get to that point though.  We'd have to _really_ loosen things up (like merge on just a 40% title match) to end up in that kind of situation.  

Erring on the side of grouping would amplify our current issues, so if we are going to group more, we'll want to merge more.

The AI-Pure automerger does check that there is only one import from AI in one publication, and only one import from Pure in the other.  It does not use any other criteria.  The reason 71509 doesn't merge is because of the other import records attached to one of the publications.  FWIW, this merge process seems to clean up a lot of duplicates whenever it's ran.  I think it was built to work with the grouping logic we currently have, so if we modify the grouping logic (to perhaps group on DOI) we'll have to consider how it will impact this automerge.

**Comment by ajkiessl** [comment]
Also, the loosening of the DOI automergeer sounds good to me.  Adding an automerger with criteria for when there are not matching DOIs (or modifying the AI-Pure automerger) sounds good too.
