### ISSUE TITLE
Reminder email went out before OA Button and Unpaywall were checked

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#551]
RMD sent an OA reminder email today for publication 511272. We have the DOI for that publication, and the creation date on the publication is September 24, 2022. Shouldn't the OA Button and Unpaywall importers have run after the publication was added, prior to the email going out?

**Comment by ajkiessl** [comment]
@anaelizabethenriquez There's a couple things going on here.  So the Open Access Button import starts on Sunday, but it looks like it takes a few days to complete.  I suppose that would make sense since it's iterating through a lot (like over 200,000 publications).  So it did not get to that Publication before the emails went out.  The Unpaywall import is similar in that it takes several days to complete, however, the Unpaywall import actually starts on Tuesday.

What we should really be doing is running our "new" imports for OAB and Unpaywall the day before emails go out.  We have a task for both the OAB import and Unpaywall import that only imports data for new records (records that do not have the open_access_button_last_checked_at or unpaywall_last_checked_at timestamps).  These imports will only have a thousand or so records to import so they shouldn't take more than an hour or two.  I'll have to double check how long the Pure import takes, and when would be a good time to run these imports.  I'm shooting for Sunday evenings, but it has to be at a time we can safely say the Pure import is done.
