### ISSUE TITLE
Remove hardcoded default_url_options

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/researcher-metadata#655]
We have the default_url_options hardcoded for the 3 rmd environments, I'm wondering if these should be config settings that are defaulted, and then overridden so that preview environemnts can work. 

We also probably want a way to send mail through a relay other than smtp.psu.edu for testing purposes. we use mailhog in some other environments, but that project also seems to be stagnent, we can use mailcatcher perhaps?

**Comment by EricDurante** [comment]
Yeah, making the ActionMailer settings configurable with defaults seems totally reasonable to me. They're only hard-coded now because the old setup was pretty rigid.

I'm not sure how much testing we do in any of the deployed environments that actually ends up sending mail. Regardless, I totally agree with your suggestion.

**Comment by ajkiessl** [comment]
I agree with what Eric said.  Mailcatcher sounds nice, but there aren't too many emails that go out that we often test.  I'd use it, though, if we add more features that send emails.  If it's not too much of a hassle, I'd say go ahead and add it.

**Comment by whereismyjetpack** [comment]
nothing is a hassle with enough coffee.
