### ISSUE TITLE
RMD admins can manually curate publications with multiple `ActivityInsightOaFile`s

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#666]
There will be instances where publications that have been merged with other publications have more than one `ActivityInsightOaFile`.  We will need a step in the workflow where these publications are listed. Clicking on a listed publication should take RMD admins to an interface to determine which one to keep and delete the others.

**Comment by ajkiessl** [comment]
We are now thinking that we could basically make this the last step, where the admin can choose which file to send off the scholarsphere.  It may be helpful to gather the file version information for all the files, and display that to the admin to help them make their choice.

**Comment by EricDurante** [comment]
I think the assumption here will be that any file that makes it to this point would be a version that is acceptable for deposit. We'll want to weed out any that aren't earlier in the workflow and kick them back to Nicole, I think (but only if we don't already have another file that _is_ the version that's acceptable for deposit).

So here the admin would presumably be choosing between files that may actually be identical, or they'd only vary in ways that don't make any of them unacceptable for deposit. If we only ever end up with identical files or with files that are so similar that the differences don't matter, then I suppose we could just automatically select one at random. Otherwise, the admin may have to actually open the files up and look at them in order to decide.

**Comment by ajkiessl** [comment]
Ah yes right.  I forgot we can determine which version is correct by using the permission data.

**Comment by ajkiessl** [comment]
Closing this since the workflow basically works this out itself.  If there are multiple files at the end of the workflow, #716 will take care of this.
