### ISSUE TITLE
Manual editing of file versions

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#689]
We do not have any edit capabilities for `ActivityInsightOaFile` within rails_admin right now.  We'll have to add that.  Then, we can link to the `ActivityInsightOaFile` edit page from the manual file version checking list.

Admins will likely want to download and view the file at this point.  We should already have the file locally, so we should link to that for the admin to view. ~~We can either directly connect to S3 in RMD, or we can integrate with the https://github.com/psu-libraries/ai-s3-authorizer .  I'm leaning toward setting up a direct S3 connection in RMD.  It may be easier to maintain that way, and be more reliable.~~

We'll want a link in the edit page for admins to download the file.  We could also make the file location in the bucket list a link to download the file.

**Comment by EricDurante** [comment]
Oh, hmm. I was assuming that we'd have to download our own copy of the file at some point (hence https://github.com/psu-libraries/researcher-metadata/issues/691) in order analyze it with exiftool and our own custom scripts and then to upload it to Scholarsphere if/when it's time to deposit. Even if it's possible to stream the files directly from S3 for all of those purposes, having a local cache of the files would prevent us from having to fetch the file over the network every time it's needed - and each file could be needed multiple times in the course of the workflow (once or twice to do automatic version checking, one or more times to be viewed/downloaded by an RMD admin, once to be sent to Scholarsphere)

**Comment by ajkiessl** [comment]
Ok, we can do that.  I was thinking we were going to keep the files as temporary as possible, so we didn't have to worry about persistent file stores.  It may be easier to just hold them on local stores, though, if we are interacting with them multiple times throughout the workflow.

**Comment by whereismyjetpack** [comment]
I don't think RMD should have a dependency on scholarsphere storage, I presume we're using CarrierWave stores for these files? If so, I think we can continue to use CarrierWave for the lifecycle of the file. We could promote CarrierWave Store to s3 if we have/want to in the future and the code shouldn't need to change much.

**Comment by EricDurante** [comment]
@whereismyjetpack Oh, sorry - here we're talking about downloading files from where they're stored when they get uploaded through Activity Insight (which happens to be in S3) to RMD's local file system so that RMD can perform a series of actions that involve reading the file without having to fetch it from S3 repeatedly for each of those actions. Does that make sense? Essentially we're talking about caching the file locally for the sake of performance.

**Comment by whereismyjetpack** [comment]
whoops. i should have read a bit closer. I think this sounds like a sane approach, right now we only have `uploads` persisted in our kubernetes environment, I hesitate to add another persistent volume for this use case, but it is a different use case, so it might make sense to have one. If we could hide this behind CarrierWave that would be nice so that the application doesn't have to be privy of the underlying storage details, but I understand if this is putting a square peg in a round hole

**Comment by EricDurante** [comment]
Yeah, agreed, I imagine that we could just keep these files in the same, existing volume and use CarrierWave to handle storage...
