### ISSUE TITLE
Retry workflow for files that cannot be deposited

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#692]
This issue is a placeholder for the whole branch of the workflow that will occur after we've identified the versions and permissions for all of a publication's files and determined that we don't have any files that can be deposited (see https://github.com/psu-libraries/researcher-metadata/issues/690). It may end up needing to be decomposed into a handful of separate issues depending on how we want this workflow to behave.

Some things that we may want to do automatically when we encounter this condition:
- delete the files that can't be deposited from Activity Insight (if possible)?
- update the publication's status in Activity Insight?
- delete the local copies of files that cannot be deposited from RMD and update RMD's associated database records to indicate that the files were not able to be deposited
- keep any metadata that we've gathered earlier in the workflow (confirmed DOI, open access information, etc.) that will be useful in the next iteration of the workflow if/when we receive a new file for the publication
- either notify the faculty member directly that we couldn't deposit the file that they provided, or notify @nmg110 so that she can contact the faculty member and help them to provide the correct version

**Comment by nmg110** [comment]
RE: either notify the faculty member directly that we couldn't deposit the file that they provided, or notify @nmg110 so that she can contact the faculty member and help them to provide the correct version

If it is a file that we cannot deposit what if they then get thrown in the OA Email group that automatically goes out from RMD? And then a list is of accounts, AI ID's, Titles, and file names are emailed to AI-Support@psu.edu for those attachments to be removed from AI? Just a thought.

**Comment by ajkiessl** [comment]
Sometimes faculty is not sure what the versions are and sending an email directly to them confuses them when the version is wrong, so sending an email to the OA group might be a better option than send to the faculty.

**Comment by ajkiessl** [comment]
We'll need to determine what exactly kicks this off.

**Comment by EricDurante** [comment]
Thanks for uncovering this additional complexity right away, @anaelizabethenriquez.

I supposed that it's possible that if one author has a batch of publications that require action, then each of those publications may require action for a different one of the reasons that you listed?

I think that by the time that a publication/file reaches this point in the workflow, we'd have enough information about the version to automatically specify the reason why the file was rejected, so that may not be an issue. If that turns out to not be the case, then we could allow the RMD admin to choose a reason (or even a whole different email template) for rejecting the file.

I also don't think that it would be too difficult to group files in this list by the Activity Insight users that uploaded them and then send one email per group that lists each file. If the files were grouped in this way, would you still want the option to send an email per file in addition to the batch email?

**Comment by EricDurante** [comment]
If the application ends up automatically deciding the reason for rejection, then I imagine that we'd want the RMD admin to be able to see that reason before they send the email in order to verify that it's correct.

I'm imagining that we may need to indicate some sort of additional state in this list also. As we've discussed, a file will eventually drop off of this list automatically once the author uploads a new (correct) file for the same publication and that file passes the version checking step. But in the meantime, the file will remain on this list. So we'll want to keep track of whether or not action has been taken for a given file (that is, whether or not an email has been sent) and probably group those files at the bottom of the list so that the files that still require action float to the top.

**Comment by anaelizabethenriquez** [comment]
Thanks, @EricDurante. This all sounds right to me. In particular:

> I supposed that it's possible that if one author has a batch of publications that require action, then each of those publications may require action for a different one of the reasons that you listed?

Yes

> If the files were grouped in this way, would you still want the option to send an email per file in addition to the batch email option?

I think so, because of the possibility that one or more files has something very weird going on and we want to just send an email about an "easy" file to get it out of the way. 

> So we'll want to keep track of whether or not action has been taken for a given file (that is, whether or not an email has been sent) and probably group those files at the bottom of the list so that the files that still require action float to the top.

Ah, right. Yes, we will definitely want to keep track of whether an email has been sent (and ideally, exactly what text was sent and when).

**Comment by ajkiessl** [comment]
This all sounds good and possible to me.  To summarize we want to:

- Include the reason the file is "wrong" in the list.  This can be automatically determined by comparing the preferred version and the determined version stored in RMD.
- Group the publications by author.
- For authors with groups of publications, add a button to send a single email to that author describing all the "wrong" files.
- Add a button for every individual publication (even the ones in groups) to send an email out to that author for just that one publication.
- Store and display info telling us if an email has already been sent.  We could track this with something like a `last_email_sent_at` timestamp.
- Order the list so that publications who've already had email notifications sent are pushed to the bottom.

**Comment by anaelizabethenriquez** [comment]
This is minor, but just to clarify: "Group the publications by author" means the author who uploaded the file in Activity Insight, not the author(s) listed in RMD.

**Comment by anaelizabethenriquez** [comment]
Per discussion with @Smullz622 , we have just a single template email for all possible cases (single vs. batch and need accepted manuscript vs. need published version). Here's the proposed text:

From: openaccess@psu.edu
Reply-to: openaccess@psu.edu
Subject: Open Access Post-Print Publication Files in Activity Insight

Hello,

We are writing to follow up on the publication file(s) uploaded to your account in Activity Insight in the section titled “Open Access Post-Print Publication files."

When researchers [upload files to this section](https://openaccess.psu.edu/deposit/activity-insight/), a team in the Libraries works to make them available to the public via [ScholarSphere](http://scholarsphere.psu.edu/) according to the default terms of the journal's publishing agreement. This process is designed for the [“post-print” or “accepted manuscript” version](https://psu.libanswers.com/faq/273465) of the article, because most journals allow that version to be shared widely. Some journals prefer that you share the final published version.

One or more of the files you uploaded appear to be a version of the article that the journal's default policy does not allow to be deposited in ScholarSphere. If you have the version of an article that can be deposited, you can send it by reply email or upload it in Activity Insight. Here is a summary of what we have and what we need:

| Title  | Version we have | Version that can be deposited |
| ------------- | ------------- | ------------- |
| [Title1]  | [ArticleVersion1]  | [PreferredVersion1] |

You can view a list of all your publications and their open access statuses on your [Manage Profile Publications page](https://metadata.libraries.psu.edu/profile/publications/edit). If you have uploaded other files in Activity Insight, we will process those files and update you in due course.

If you have any questions, please do not hesitate to contact us at [openaccess@psu.edu](mailto:openaccess@psu.edu).

All the best,
Office of Scholarly Communications and Copyright
Penn State University Libraries
openaccess@psu.edu

**Comment by anaelizabethenriquez** [comment]
Thanks, @nmg110 ! I just updated the text to "One or more of the files you (or an Activity Insight Proxy) uploaded..."

**Comment by anaelizabethenriquez** [comment]
Just a quick note to say that if "Preferred Version" is "none" for a publication, we don't want to include it in this email/bucket. Those items should be in a different bucket.
