### ISSUE TITLE
Server error when uploading to ScholarSphere from RMD

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#721]
User ljv4 reported an error when uploading to ScholarSphere from RMD and provided the attached screenshot. They are a Hershey user. I also noticed that the error message doesn't give a support email address.

![image001](https://user-images.githubusercontent.com/43611017/222501088-f4319698-147e-469f-9efe-4de81476b3d5.png)

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Hi Ana, welcome back.  Did the user say when this happened?  I'm not seeing any errors in our logs related to this.  If it was done sometime in the middle of the night, they might have timed it just as the server was rebooting.

**Comment by ajkiessl** [comment]
Ah never mind, I see a timeout error at about 11:09 AM yesterday associated with this user.  Looking into what might have caused this.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez We've dug into this further and we think that the application server is timing out because the exif file version checking is taking too long for this file.  It's either that, or the user's internet connection is very slow.  Assuming that the issue _is_ the exif version checking, we increased the amount of time it takes for the server to timeout.  This has been deployed to production.

Can we get the user to try uploading again?  If there is still an issue, then I think we are going to have to try proxy uploading for this user.

**Comment by ajkiessl** [comment]
Ok, sounds good.  Thanks!
