### ISSUE TITLE
Make License field a drop-down menu

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#790]
When admins edit the "License" field, there should be a drop-down menu of options. Right now this field takes free text.

I am not sure if there is currently any validation on this field, but there should be. I believe ScholarSphere will not accept an incoming deposit if the license doesn't match an allowable license option. This is why the field is a drop-down in the regular ScholarSphere deposit workflow in RMD.

I suspect OA Button may be providing a wider range of options in this field than ScholarSphere allows, so we may need to think about mapping them (or updating ScholarSphere to allow other licenses).

**Comment by ajkiessl** [comment]
We actually already have a mapping class for mapping the license format from OAB to our format.  We added this when we implemented the original ScholarSphere deposit version and permission checking (https://github.com/psu-libraries/researcher-metadata/pull/569).  We may want to review it, though, to see if anything has been added to OAB.

**Comment by EricDurante** [comment]
@anaelizabethenriquez Good catch. The information that gets submitted to ScholarSphere in the RMD's self-serve deposit workflow is represented by a different data model in RMD that gets populated by a combination of metadata from a publication record and direct user input. This model _does_ have a validation on its license field, but the publication model in RMD currently does not.

Is there any way to know all of the possible license values that OA Button may report and whether or not that list is subject to change without notice?

If we add a validation to the license field on the publication model, then OA Button could break our automatic permissions checking for some publications simply by adding a new license value. If that's a possibility, then we may not want it to work that way. What we definitely could do, as you suggested, would be to make the license field a drop-down of known values in the Rails Admin edit view for publications. That would at least ensure that admins are entering valid data that will be accepted by ScholarSphere, but it would also still allow the field to be populated with whatever value OA Button provides.

When it comes time to do the ScholarSphere deposit in the DM-OA workflow, then I guess we have a choice - we could just allow ScholarSphere to do all of the metadata validation since it's the authority on those rules, or we could attempt to duplicate ScholarSphere's validations in RMD (as we've done with the self-serve workflow) to try to prevent invalid submissions in the first place.

I think I'd actually lean toward the former as long as ScholarSphere provides structured, machine-readable data in its error responses (I actually can't remember). That way, if we got a new license value from OA Button that we weren't expecting and that ScholarSphere won't accept, we could allow the deposit to be attempted, and allow ScholarSphere to tell us that the license isn't valid. Then we'd know that we need to do one or more of the following:

- edit that license value to make it something that ScholarSphere will accept
- create an automatic mapping from the new OAB license value to an existing one that ScholarSphere already accepts
- actually update ScholarSphere to accept a totally new license value (and update our list of allowable license values in the RMD drop-downs)
- perhaps totally reject the deposit if the license really isn't acceptable in ScholarSphere for some reason?

**Comment by anaelizabethenriquez** [comment]
Thanks @ajkiessl @EricDurante !

If we need to review the license manually, it would be nice to take care of that during the "Review Permissions" step. So, could we just say that if the data coming from OAB doesn't fit into our current mapping, we leave the field blank, which would send it to the manual permissions review queue?

**Comment by ajkiessl** [comment]
> Is there any way to know all of the possible license values that OA Button may report and whether or not that list is subject to change without notice?

iirc I determined the mapping by finding all the unique license values in the "Data Download" here: https://shareyourpaper.org/permissions/about#api .  Not sure if this is _all_ the permissions data in OAB.  It's only about 10,000 records.  I also programmatically tried to find all the unique licenses by sending a request for a subset of our publications in RMD.  I forget how many that was, and if there was anything that didn't overlap with the unique values from the "Data Download".  I think the only differences between the "Data Download" and API was that the "Data Download" returns their licenses in all-caps, but the API was all lowercase.

> So, could we just say that if the data coming from OAB doesn't fit into our current mapping, we leave the field blank, which would send it to the manual permissions review queue?

That sounds good to me.  This would force us to evaluate that license and then potentially add it to our list of acceptable licenses.  We'd have to modify the current state of the mapper, though.  Right now it defaults to "All Rights Reserved" for these cases.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Is this on QA? I'm not seeing it, but maybe I'm not looking in the right place.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Never mind my comment above. We discussed this in standup. I had been looking at the old metadata fields, which will be removed (see #830). The drop-down is present in the new fields on the file record.
