### ISSUE TITLE
Refine the set of publications subject to the AI OA workflow

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#797]
Currently, if a publication has a file from Activity Insight, RMD checks for an OA location. If the publication has an OA location, the publication does not go through the AI OA workflow.

Instead, we should check the "Open access status" field and check for a ScholarSphere open access location.

- If the "open access status" is "gold" or "hybrid", or if there is a ScholarSphere open access location, the publication should not go through the AI OA workflow. RMD should report to AI that the publication is already openly available. This information should be passed along to the AI user via the AI field that RMD calls "Activity insight postprint status." The file should either be removed from RMD or not imported.
- If the "open access status" is "green", "bronze", or "closed" and there is no ScholarSphere open access location, the publication should go through the AI OA workflow.

**Comment by EricDurante** [comment]
Are there situations where a publication may already have one or more open access locations listed in RMD, but we'd still want it to go through this workflow and possibly be deposited into ScholarSphere? I feel like we've discussed this before, but I just can't remember all of the details (or how to find where they were recorded) - my apologies.

**Comment by EricDurante** [comment]
So it sounds like a publication could have "green", "bronze", or "closed" OA status _and_ already have an open access location that is _not_ ScholarSphere, and in that case we'd want to try to deposit in ScholarSphere?

**Comment by anaelizabethenriquez** [comment]
> Are there situations where a publication may already have one or more open access locations listed in RMD, but we'd still want it to go through this workflow and possibly be deposited into ScholarSphere? 

Yes, @EricDurante 

> So it sounds like a publication could have "green", "bronze", or "closed" OA status and already have an open access location that is _not_ ScholarSphere, and in that case we'd want to try to deposit in ScholarSphere?

Correct.

If the status is "green" or "bronze", there should always be at least one OA link. If there's a ScholarSphere link, we don't want to deposit because we don't want duplicates in ScholarSphere. Otherwise, though, we do want to deposit.  The reason for this is that "bronze" often turns back into "closed". With "green", it's pretty unlikely that would happen, but since the AI user has essentially asked us to deposit the file in ScholarSphere, we're putting a thumb on the scale to follow their wishes (whereas with "gold" or "hybrid" we are going to disregard their wishes). We definitely talked about this during the design phase, but I'm not seeing it documented in github.

**Comment by EricDurante** [comment]
Ok, here's my rough idea for this in terms of implementation - please scrutinize:

- We can change the base filter (`Publication.activity_insight_oa_publication`) for publications that belong in this workflow so that only publications that already have ScholarSphere open access locations are excluded as opposed to excluding publications with any open access locations. We may need to change [this logic](https://github.com/psu-libraries/researcher-metadata/blob/534448297d0c19236916448649109d5eb4454edb/app/models/publication.rb#L517) as well.
- Automatically retrieving open access status info is going to be dependent on knowing and verifying DOI, so all publications with a file and with no ScholarSphere open access location are still going to need to enter at least the first parts of the workflow.
- We'll need to update the existing step in the workflow that fetches OA metadata from OAB and Unpaywall so that it always pulls in open access status from Unpaywall.
- Publications that have both a verified DOI and a timestamp indicating that their OA metadata has been checked but that have no open access status are going to need to be kicked out for manual review at some point. Maybe presence of OA status becomes another criterion for not being included in the manual permissions review list? Not sure if that makes sense or if it would be better to catch this earlier in its own bucket...
- Once we know open access status, we can use a status of "gold" or "hybrid" to filter publications out of the subsequent steps.

**Comment by EricDurante** [comment]
> We definitely talked about this during the design phase, but I'm not seeing it documented in github.

Ah yes - I recall now. Sorry again that I was foggy on the details.

**Comment by anaelizabethenriquez** [comment]
No worries!

> We'll need to update the existing step in the workflow that fetches OA metadata from OAB and Unpaywall so that it always pulls in open access status from Unpaywall.

I suspect in this workflow we are currently only pulling permissions metadata from OAB's permissions API. But RMD is importing open access status from Unpaywall for all publications (maybe not at exactly the right time for things that get DOIs added/confirmed in this workflow).

**Comment by anaelizabethenriquez** [comment]
Related #653
