### ISSUE TITLE
List for Publications whose file versions are all determined but Preferred Version is "None"

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#799]
Related to #692 

Most of the time, if we can’t deposit the version that we got, there’s another version we can deposit (see #719, the "wrong version" bucket). But, sometimes there won’t be any version of the article that we can deposit. For these publications, an admin will set the "preferred_version" to "None". We need to add that as an option for that field. 

We don’t want those to show up in the “wrong version” bucket — they should be in a bucket of their own called "Publications for which no version can be deposited". The logic for this list is the same as the "wrong version" bucket except that "preferred_version" is "None".

In this list, an admin should be able to review the item and should be able to send the user an email explaining that no version of the publication can be deposited. This functionality can be very similar to the "wrong version" bucket, except that once we've sent an email to the user we are not waiting on any further action, so the publication(s) we emailed them about should be removed from the list. An admin should be able to send an email about just one publication or a batch of publications from a particular user.

When the publications are removed from the list (when the email is sent successfully), RMD should also:

- ~~delete the files that can't be deposited from Activity Insight (if possible)?~~
- update the publication's status in Activity Insight to "Cannot Deposit"
- delete the local copies of files that cannot be deposited from RMD and update RMD's associated database records to indicate that the files were not able to be deposited

We'll need to keep some record of the fact that we've sent this email for a given publication in order to know which publications to show in this list, but this record will also indicate that the publication has completely exited this workflow, so it will make sense to include its presence as another filter in the `Publication#activity_insight_oa_publication` scope and in any appropriate scope(s) on `ActivityInsightOAFile` so that it doesn't appear in any other lists and so that it's not subject to any more automated processing.

**Comment by ajkiessl** [comment]
Update Activity Insight and send the email at the same time.

**Comment by Smullz622** [comment]
@anaelizabethenriquez when you get the chance, could you add what you'd like in the email please?

**Comment by anaelizabethenriquez** [comment]
Sorry about that! Here it is:

From: openaccess@psu.edu
Reply-to: openaccess@psu.edu
Subject: Open Access Post-Print Publication Files in Activity Insight

Hello,

We are writing to follow up on the publication file(s) uploaded to your account in Activity Insight in the section titled “Open Access Post-Print Publication files."

When researchers [upload files to this section](https://openaccess.psu.edu/deposit/activity-insight/), a team in the Libraries works to make them available to the public via [ScholarSphere](http://scholarsphere.psu.edu/) according to the default terms of the journal's publishing agreement. This process is designed for the [“post-print” or “accepted manuscript” version](https://psu.libanswers.com/faq/273465) of the article, because most journals allow that version to be shared widely. Some journals prefer that you share the final published version. In rare cases, the journal does not allow you to share either version.

This is the case for the following article(s) for which you (or an Activity Insight Proxy) uploaded files:

[Title1]
[additional titles as needed]

As a result, we have not deposited the file(s). If you believe this is an error, if you would like us enter a waiver of the OA policy for this article, or if you have any questions, please do not hesitate to contact us at [openaccess@psu.edu](mailto:openaccess@psu.edu).

If you have uploaded other files in Activity Insight, we will process those files and update you in due course. You can view a list of all your publications and their open access statuses on your [Manage Profile Publications page](https://metadata.libraries.psu.edu/profile/publications/edit). 

All the best,
Office of Scholarly Communications and Copyright
Penn State University Libraries
openaccess@psu.edu

**Comment by Smullz622** [comment]
@ajkiessl can I get your opinion on how to execute the email step with the 'Cannot Deposit' export to Activity Insight? Since the plan is to do these simultaneously, here's what I'm thinking: The email controller action will send an email, trigger the export job on all files for the publication, and then update a boolean on publication to indicate that the email has been sent. That boolean will filter the publication out of the workflow moving forward. I don't think there needs to be a boolean on the file indicating it's been exported, but instead if it fails, have the job trigger an error. What do you think? Am I missing anything with that process?

**Comment by ajkiessl** [comment]
@Smullz622 Yeah I think that sounds good.  We probably want to set the boolean right after the email is sent but before the export job is queued, though.  That way if there's an error with delayed job, then the boolean will still be set and indicate to us that the email was sent.

I agree that we shouldn't need to store a boolean with the file regarding the status update in Activity Insight.  Since the publication will fall out of the workflow, there won't be a way for anyone to accidentally send the emails again, so we don't need a boolean for that.  If the email boolean on the publication is updated, then we know the status in Activity Insight should have been updated (unless there was an error), so we don't need a boolean for that.  Otherwise, I can't think of any other reason why we might need the boolean on the file.

**Comment by anaelizabethenriquez** [comment]
@Smullz622 This is very minor. When testing, I noticed a typo in the email text. Can you add a period after "please do not hesitate to contact us at [openaccess@psu.edu](mailto:openaccess@psu.edu)"?

**Comment by Smullz622** [comment]
> @Smullz622 This is very minor. When testing, I noticed a typo in the email text. Can you add a period after "please do not hesitate to contact us at [openaccess@psu.edu](mailto:openaccess@psu.edu)"?

No problem!
