### ISSUE TITLE
Organizational demo pages

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#828]
Copied from https://github.com/psu-libraries/researcher-metadata/issues/774#issuecomment-1734420281 we want:

Organizational demo pages that display publications for each organization and paginate in groups of 25, in reverse chronological order by publication date

How will user find the page for the Organization they want? For now we would just use the Org's ID in the URL so we can predict the URL and provide it as needed.

Within the Libraries, we'd want to implement our own page pulling content from the API. But, we won't be able to do this immediately, so we would link out to the demo page in the meantime.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl One more thought I had after looking at the preview -- could you add contact details in the footer so folks know whom to contact about corrections/errors? I'm thinking something like "With corrections or questions, please contact Faculty Activity Management Services, University Libraries, L-FAMS@lists.psu.edu."

I'm suggesting the FAMS contact info since that's what's on the main page and I think they are best placed to handle most errors with these publication lists, but tagging @nmg110 in case she disagrees. If Nicole prefers, we can do ""With corrections or questions, please contact Scholarly Communications and Copyright, University Libraries, openaccess@psu.edu."

**Comment by nmg110** [comment]
@anaelizabethenriquez I am good with what @ajkiessl has. Most of the time it is an issue with their Activity Insight data anyway. :-)
