### ISSUE TITLE
Publications Validations

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#85]
Validations for ISBN/ISSN/DOIs.  This can either be on the model level or at import.  

Having model level validations will give us more universal control over what gets into the database.  As of right now our biggest issue is data coming in from Digital Measures.  Sometimes the data is either wrong, or placed in the wrong field (ie a doi in the isbn/issn field).  This is where validating on import might be a better solution, since we could detect identifiers in the wrong field and put them in the right place on import.

It might make sense to implement both of these.  Model level validations for universal use, and something that detects identifiers in the wrong fields during the DM import.

**Comment by ajkiessl** [comment]
1b5e0b2af66f0ec5a77834b65e48159b38fd9e88

**Comment by ajkiessl** [comment]
@EricDurante Since we already have a DOIParser and now have a DOI field in Activity Insight, I think we just need something that can differentiate between ISSNs and ISBNs from AI?  I think this only needs to be applied to the AI importer, since the other resources don't seem to give us isbns.

The data coming from Pure has an "isbns" element in the JSON output.  I can have the Pure importer import this.  It currently is not importing isbns.

**Comment by EricDurante** [comment]
@ajkiessl That all sounds accurate/good to me. It would be good to have our definition of valid DOI format in only one place if possible (especially so since I don't know if our definition is 100% correct, and so it might have to be tweaked in the future).

Is the plan still to check each field (DOI, ISSN, ISBN, URL, etc.) from AI for a valid DOI, ISSN, or ISBN value and take values that are entered in the incorrect place in AI and put them in the correct place in RMD? If so, then we'll probably need to establish single definitions of ISSN and ISBN validity somewhere too.

**Comment by ajkiessl** [comment]
@EricDurante  Yeah I'll stick to that plan.  I was considering model level validations for publications to check that DOIs, ISBNs, and ISSNs match their corresponding regexes.  I think that might be too restrictive.  I don't want to implement something that will affect the other imports, since AI seems to be the primary source of this problem.  For now, I'll implement something like the DOIParser for ISSNs and ISBNs that can be used to get incorrect values in AI put in the right place in RMD.
